local function AddQuagmirePrefix(prefab)
    CopyPrefabDescriptions("quagmire_" .. prefab, prefab)
end

local function ReplaceQuagmirePrefix(prefab)
    CopyPrefabDescriptions("quagmire_" .. prefab, "gorge_" .. prefab)
end

ReplaceQuagmirePrefix("goatmum")
ReplaceQuagmirePrefix("altar")
ReplaceQuagmirePrefix("goatmilk")
ReplaceQuagmirePrefix("key")
AddQuagmirePrefix("pond_salt")
AddQuagmirePrefix("pebblecrab")
AddQuagmirePrefix("pigeon")
AddQuagmirePrefix("wheat")
AddQuagmirePrefix("turnip")
AddQuagmirePrefix("onion")
AddQuagmirePrefix("garlic")
AddQuagmirePrefix("tomato")
AddQuagmirePrefix("potato")
AddQuagmirePrefix("pot_hanger")
AddQuagmirePrefix("pot")
AddQuagmirePrefix("pot_small")
AddQuagmirePrefix("pot_syrup")
AddQuagmirePrefix("grill")
AddQuagmirePrefix("grill_small")
AddQuagmirePrefix("grill_item")
AddQuagmirePrefix("grill_small_item")
AddQuagmirePrefix("oven")
AddQuagmirePrefix("oven_item")
AddQuagmirePrefix("casseroledish")
AddQuagmirePrefix("casseroledish_small")
AddQuagmirePrefix("syrup")
AddQuagmirePrefix("sap")
AddQuagmirePrefix("salt_rack")
AddQuagmirePrefix("salt_rack_item")
AddQuagmirePrefix("salt")
AddQuagmirePrefix("saltrock")
AddQuagmirePrefix("mealingstone")
AddQuagmirePrefix("sapbucket")
AddQuagmirePrefix("flour")
AddQuagmirePrefix("coin1")
AddQuagmirePrefix("coin2")
AddQuagmirePrefix("coin3")
AddQuagmirePrefix("coin4")
AddQuagmirePrefix("crate")
AddQuagmirePrefix("salmon")
AddQuagmirePrefix("crabmeat")
AddQuagmirePrefix("plate_silver")
AddQuagmirePrefix("bowl_silver")
CopyPrefabDescriptions("quagmire_swampigelder", "gorge_swamppig_elder")
CopyPrefabDescriptions("quagmire_swampig", "gorge_swamppig")
