modimport("lib/custom_tech_tree")
modimport("init/init_config")
modimport("init/init_chat")
modimport("utils/utils_common")
modimport("utils/utils_main")
modimport("utils/utils_console")
modimport("init/init_named")
modimport("init/init_containers")
modimport("init/init_assets")
modimport("init/init_actions")
modimport("init/init_prefabs")
modimport("init/init_names")
modimport("init/init_descriptions")
modimport("init/init_recipes")
modimport("init/init_cookpot")

modimport("init/postinits/postinit_edible")
modimport("init/postinits/postinit_saltable")
modimport("init/postinits/postinit_actionhandlers")
modimport("init/postinits/postinit_world")

modimport("init/init_compatibility")
